"""Container file generation for CI/CD & Verification.

Generates Dockerfile, docker-compose.yml, and .dockerignore
for detected project frameworks.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from .config import CICDConfig
from .models import Framework, FrameworkInfo, PackageManager

# Base images per framework (specific version tags, never 'latest')
_BASE_IMAGES: dict[Framework, str] = {
    Framework.PYTHON: "python:3.12-slim",
    Framework.NODE: "node:20-alpine",
    Framework.GO: "golang:1.22-alpine",
    Framework.RUST: "rust:1.77-slim",
    Framework.MULTI: "ubuntu:24.04",
    Framework.UNKNOWN: "ubuntu:24.04",
}

# Runtime images (smaller, for final stage)
_RUNTIME_IMAGES: dict[Framework, str] = {
    Framework.PYTHON: "python:3.12-slim",
    Framework.NODE: "node:20-alpine",
    Framework.GO: "gcr.io/distroless/static-debian12",
    Framework.RUST: "debian:bookworm-slim",
    Framework.MULTI: "ubuntu:24.04",
    Framework.UNKNOWN: "ubuntu:24.04",
}

# Dockerignore patterns per framework
_IGNORE_PATTERNS: dict[Framework, list[str]] = {
    Framework.PYTHON: [
        "__pycache__", "*.pyc", "*.pyo", ".venv", "venv",
        ".pytest_cache", ".mypy_cache", ".ruff_cache",
        "dist", "build", "*.egg-info",
        ".coverage", "htmlcov",
    ],
    Framework.NODE: [
        "node_modules", "dist", "build", ".next", ".nuxt",
        "coverage", ".cache", "*.log",
    ],
    Framework.GO: [
        "bin/", "vendor/", "coverage.out",
    ],
    Framework.RUST: [
        "target/", "*.rs.bk",
    ],
}

# Common ignore patterns (all frameworks)
_COMMON_IGNORE = [
    ".git", ".github", ".claude", ".specify",
    ".env", ".env.*", "*.env",
    ".DS_Store", "Thumbs.db",
    "*.md", "LICENSE", "Makefile",
    ".dockerignore", "Dockerfile", "docker-compose.yml",
]


def generate_dockerfile(info: FrameworkInfo, config: Optional[CICDConfig] = None) -> str:
    """Generate a multi-stage Dockerfile for the detected framework."""
    if config is None:
        config = CICDConfig()

    base_image = config.container.base_image
    if base_image == "auto":
        base_image = _BASE_IMAGES.get(info.framework, _BASE_IMAGES[Framework.UNKNOWN])

    runtime_image = _RUNTIME_IMAGES.get(info.framework, _RUNTIME_IMAGES[Framework.UNKNOWN])
    ports = config.container.expose_ports or [8000]
    health_url = _get_health_url(config, ports[0])

    generators = {
        Framework.PYTHON: _dockerfile_python,
        Framework.NODE: _dockerfile_node,
        Framework.GO: _dockerfile_go,
        Framework.RUST: _dockerfile_rust,
    }

    generator = generators.get(info.framework, _dockerfile_generic)
    return generator(info, config, base_image, runtime_image, ports, health_url)


def generate_compose(info: FrameworkInfo, config: Optional[CICDConfig] = None) -> str:
    """Generate docker-compose.yml content."""
    if config is None:
        config = CICDConfig()

    ports = config.container.expose_ports or [8000]
    lines: list[str] = []
    lines.append("services:")
    lines.append("  app:")
    lines.append("    build: .")
    for port in ports:
        if lines[-1].startswith("    build"):
            lines.append("    ports:")
        lines.append(f'      - "{port}:{port}"')
    lines.append("    env_file:")
    lines.append("      - .env")
    lines.append("    restart: unless-stopped")

    # Add configured services
    for svc in config.container.compose_services:
        name = svc.get("name", "service")
        image = svc.get("image", "")
        svc_ports = svc.get("ports", [])
        svc_env = svc.get("environment", {})
        svc_volumes = svc.get("volumes", [])

        lines.append("")
        lines.append(f"  {name}:")
        if image:
            lines.append(f"    image: {image}")
        if svc_ports:
            lines.append("    ports:")
            for p in svc_ports:
                lines.append(f'      - "{p}"')
        if svc_env:
            lines.append("    environment:")
            for k, v in svc_env.items():
                lines.append(f"      {k}: {v}")
        if svc_volumes:
            lines.append("    volumes:")
            for v in svc_volumes:
                lines.append(f"      - {v}")
        lines.append("    restart: unless-stopped")

    lines.append("")
    return "\n".join(lines)


def generate_dockerignore(info: FrameworkInfo) -> str:
    """Generate .dockerignore content."""
    patterns = list(_COMMON_IGNORE)
    fw_patterns = _IGNORE_PATTERNS.get(info.framework, [])
    patterns.extend(fw_patterns)

    # Deduplicate preserving order
    seen: set[str] = set()
    unique: list[str] = []
    for p in patterns:
        if p not in seen:
            seen.add(p)
            unique.append(p)

    lines = ["# Auto-generated by lib/cicd container"]
    lines.append("")
    lines.append("# Common")
    for p in _COMMON_IGNORE:
        lines.append(p)
    if fw_patterns:
        lines.append("")
        lines.append(f"# {info.framework.label}")
        for p in fw_patterns:
            lines.append(p)
    lines.append("")
    return "\n".join(lines)


def generate_container_files(
    info: FrameworkInfo,
    config: Optional[CICDConfig] = None,
    output_dir: Optional[str] = None,
) -> dict[str, str]:
    """Generate all container files.

    Returns dict mapping filenames to content.
    Optionally writes to disk if output_dir provided.
    """
    if config is None:
        config = CICDConfig()

    files: dict[str, str] = {
        "Dockerfile": generate_dockerfile(info, config),
        ".dockerignore": generate_dockerignore(info),
    }

    if config.container.compose_services:
        files["docker-compose.yml"] = generate_compose(info, config)

    if output_dir:
        root = Path(output_dir)
        for filepath, content in files.items():
            full_path = root / filepath
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)

    return files


# ---------------------------------------------------------------------------
# Framework-specific Dockerfile generators
# ---------------------------------------------------------------------------

def _get_health_url(config: CICDConfig, default_port: int) -> str:
    """Get health check URL from config or default."""
    if config.health.endpoints:
        return config.health.endpoints[0].url
    return f"http://localhost:{default_port}/health"


def _dockerfile_python(
    info: FrameworkInfo,
    config: CICDConfig,
    base_image: str,
    runtime_image: str,
    ports: list[int],
    health_url: str,
) -> str:
    uses_uv = info.package_manager == PackageManager.UV
    lines: list[str] = []

    lines.append(f"FROM {base_image} AS builder")
    lines.append("")
    lines.append("WORKDIR /app")
    lines.append("")

    if uses_uv:
        lines.append("# Install uv")
        lines.append("COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv")
        lines.append("")
        lines.append("# Install dependencies (cached layer)")
        lines.append("COPY pyproject.toml uv.lock* ./")
        lines.append("RUN uv sync --frozen --no-dev --no-install-project")
        lines.append("")
        lines.append("# Copy source and install project")
        lines.append("COPY . .")
        lines.append("RUN uv sync --frozen --no-dev")
    else:
        lines.append("# Install dependencies (cached layer)")
        lines.append("COPY requirements*.txt ./")
        lines.append("RUN pip install --no-cache-dir -r requirements.txt")
        lines.append("")
        lines.append("# Copy source")
        lines.append("COPY . .")

    lines.append("")
    lines.append(f"FROM {runtime_image}")
    lines.append("")
    lines.append("WORKDIR /app")
    lines.append("")
    lines.append("# Create non-root user")
    lines.append("RUN groupadd -r appuser && useradd -r -g appuser appuser")
    lines.append("")

    if uses_uv:
        lines.append("# Copy virtual environment from builder")
        lines.append("COPY --from=builder /app/.venv /app/.venv")
        lines.append("COPY --from=builder /app /app")
        lines.append("ENV PATH=\"/app/.venv/bin:$PATH\"")
    else:
        lines.append("# Copy installed packages and source from builder")
        lines.append("COPY --from=builder /usr/local/lib/python3.12 /usr/local/lib/python3.12")
        lines.append("COPY --from=builder /usr/local/bin /usr/local/bin")
        lines.append("COPY --from=builder /app /app")

    lines.append("")
    for port in ports:
        lines.append(f"EXPOSE {port}")
    lines.append("")
    lines.append("USER appuser")
    lines.append("")
    lines.append('HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\')
    lines.append(f'  CMD curl -f {health_url} || exit 1')
    lines.append("")
    lines.append('CMD ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]')
    lines.append("")
    return "\n".join(lines)


def _dockerfile_node(
    info: FrameworkInfo,
    config: CICDConfig,
    base_image: str,
    runtime_image: str,
    ports: list[int],
    health_url: str,
) -> str:
    uses_yarn = info.package_manager == PackageManager.YARN
    lines: list[str] = []

    lines.append(f"FROM {base_image} AS builder")
    lines.append("")
    lines.append("WORKDIR /app")
    lines.append("")
    lines.append("# Install dependencies (cached layer)")

    if uses_yarn:
        lines.append("COPY package.json yarn.lock ./")
        lines.append("RUN yarn install --frozen-lockfile --production=false")
    else:
        lines.append("COPY package.json package-lock.json* ./")
        lines.append("RUN npm ci")

    lines.append("")
    lines.append("# Copy source and build")
    lines.append("COPY . .")
    lines.append("RUN npm run build 2>/dev/null || true")
    lines.append("")
    lines.append(f"FROM {runtime_image}")
    lines.append("")
    lines.append("WORKDIR /app")
    lines.append("")
    lines.append("# Create non-root user")
    lines.append("RUN addgroup -S appuser && adduser -S appuser -G appuser")
    lines.append("")
    lines.append("# Copy production dependencies and build output")
    lines.append("COPY --from=builder /app/node_modules ./node_modules")
    lines.append("COPY --from=builder /app/dist ./dist 2>/dev/null || true")
    lines.append("COPY --from=builder /app/build ./build 2>/dev/null || true")
    lines.append("COPY --from=builder /app/package.json ./")
    lines.append("")

    for port in ports:
        lines.append(f"EXPOSE {port}")
    lines.append("")
    lines.append("USER appuser")
    lines.append("")
    lines.append('HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\')
    lines.append(f'  CMD wget -qO- {health_url} || exit 1')
    lines.append("")
    lines.append('CMD ["node", "dist/index.js"]')
    lines.append("")
    return "\n".join(lines)


def _dockerfile_go(
    info: FrameworkInfo,
    config: CICDConfig,
    base_image: str,
    runtime_image: str,
    ports: list[int],
    health_url: str,
) -> str:
    lines: list[str] = []

    lines.append(f"FROM {base_image} AS builder")
    lines.append("")
    lines.append("WORKDIR /app")
    lines.append("")
    lines.append("# Download dependencies (cached layer)")
    lines.append("COPY go.mod go.sum ./")
    lines.append("RUN go mod download")
    lines.append("")
    lines.append("# Build static binary")
    lines.append("COPY . .")
    lines.append("RUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-w -s' -o /app/server ./...")
    lines.append("")
    lines.append(f"FROM {runtime_image}")
    lines.append("")
    lines.append("# Copy binary from builder")
    lines.append("COPY --from=builder /app/server /server")
    lines.append("")
    for port in ports:
        lines.append(f"EXPOSE {port}")
    lines.append("")
    lines.append("# Run as non-root (distroless uses numeric UID)")
    lines.append("USER 65534")
    lines.append("")
    lines.append('ENTRYPOINT ["/server"]')
    lines.append("")
    return "\n".join(lines)


def _dockerfile_rust(
    info: FrameworkInfo,
    config: CICDConfig,
    base_image: str,
    runtime_image: str,
    ports: list[int],
    health_url: str,
) -> str:
    lines: list[str] = []

    lines.append(f"FROM {base_image} AS builder")
    lines.append("")
    lines.append("WORKDIR /app")
    lines.append("")
    lines.append("# Cache dependencies")
    lines.append("COPY Cargo.toml Cargo.lock ./")
    lines.append("RUN mkdir src && echo 'fn main() {}' > src/main.rs")
    lines.append("RUN cargo build --release && rm -rf src target/release/deps/app*")
    lines.append("")
    lines.append("# Build actual binary")
    lines.append("COPY . .")
    lines.append("RUN cargo build --release")
    lines.append("")
    lines.append(f"FROM {runtime_image}")
    lines.append("")
    lines.append("# Install curl for healthcheck")
    lines.append("RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*")
    lines.append("")
    lines.append("# Create non-root user")
    lines.append("RUN groupadd -r appuser && useradd -r -g appuser appuser")
    lines.append("")
    lines.append("# Copy binary from builder")
    lines.append("COPY --from=builder /app/target/release/app /usr/local/bin/app")
    lines.append("")
    for port in ports:
        lines.append(f"EXPOSE {port}")
    lines.append("")
    lines.append("USER appuser")
    lines.append("")
    lines.append('HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\')
    lines.append(f'  CMD curl -f {health_url} || exit 1')
    lines.append("")
    lines.append('CMD ["app"]')
    lines.append("")
    return "\n".join(lines)


def _dockerfile_generic(
    info: FrameworkInfo,
    config: CICDConfig,
    base_image: str,
    runtime_image: str,
    ports: list[int],
    health_url: str,
) -> str:
    lines: list[str] = []

    lines.append(f"FROM {base_image}")
    lines.append("")
    lines.append("WORKDIR /app")
    lines.append("")
    lines.append("# Create non-root user")
    lines.append("RUN groupadd -r appuser && useradd -r -g appuser appuser")
    lines.append("")
    lines.append("COPY . .")
    lines.append("")
    for port in ports:
        lines.append(f"EXPOSE {port}")
    lines.append("")
    lines.append("USER appuser")
    lines.append("")
    lines.append('CMD ["bash"]')
    lines.append("")
    return "\n".join(lines)
